server :
  port : 8080

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/lims?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

mybatis :
  mapper-locations: classpath:/mappers/**/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml
  type-aliases-package: lims.api

logging:
  level:
    com.zaxxer.hikari.HikariConfig: debug
    com.zaxxer.hikari: trace
    root: info
    lims.api: info
    jdbc.resultsettable: debug
    jdbc.sqltiming: debug
    jdbc: off
    jdbc.audit: off
    jdbc.sqlonly: off
    jdbc.resultset: off
    jdbc.connection: info
  file :
    path : C:\dev\mybatis-log






