server :
  port : 8080
  servlet:
    encoding :
      charset: UTF-8
      enabled: true
      force : true
  shutdown: graceful
  tomcat:
    connection-timeout: 90s
    max-connections: 50
  error :
    include-message: always
    include-stacktrace: never
    include-binding-errors: always
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/lims?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  hikari:
    maximum-pool-size: 10
    connection-timeout: 60000
    max-lifetime: 25200000


mybatis :
  mapper-locations: classpath:/mappers/**/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml
  type-aliases-package: lims.api

logging:
  level:
    com.zaxxer.hikari.HikariConfig: debug
    com.zaxxer.hikari: warn
    root: info
    org.mybatis: WARN            # MyBatis
    lims.api: debug
    jdbc.resultsettable: off
    jdbc.sqltiming: off
    jdbc: off
    jdbc.audit: off
    jdbc.sqlonly: off
    jdbc.resultset: off
    jdbc.connection: off
  file :
    path : C:\dev\mybatis-log
    logback :
      rollingpolicy :
        max-file-size : 10MB
        clean-history-on-start : false






